import {formatR} from "./riskData.mjs";
import {analyzeBehavior,behaviorSummary} from "./behavior.js";
import {answerQuestion} from "./coach.js";
import {engineFetch} from "./engine.js";

const money=n=>(n<0?"-$":"$")+Math.abs(Number(n)||0).toLocaleString(undefined,{maximumFractionDigits:0});
const signed=n=>n>=0?"+"+money(n):money(n);
const pct=n=>Number(n||0).toFixed(1)+"%";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function bars(rows,value="pnl",limit=6){const data=rows.slice(0,limit);if(!data.length)return '<div class="empty-state">More executions needed.</div>';const max=Math.max(1,...data.map(x=>Math.abs(Number(x[value])||0)));return '<div class="bar-chart">'+data.map(x=>'<div class="bar-row"><span>'+esc(x.name)+'</span><div class="bar-track"><i class="'+(x[value]>=0?"positive":"negative")+'" style="width:'+Math.max(4,Math.abs(x[value])/max*100)+'%"></i></div><b class="'+(x[value]>=0?"up":"down")+'">'+signed(x[value])+'</b></div>').join("")+'</div>';}
function pie(rows){const data=rows.filter(x=>x.trades>0).slice(0,6),total=data.reduce((s,x)=>s+x.trades,0)||1;let start=0;const colors=["#6fe0a3","#78a8ff","#d5a6ff","#f6c56b","#ef8d98","#67d7d1"];const stops=data.map((x,i)=>{const a=start/total*100;start+=x.trades;return colors[i%colors.length]+" "+a+"% "+(start/total*100)+"%";}).join(",");return '<div class="pie-wrap"><div class="pie" style="background:conic-gradient('+stops+')"></div><div class="pie-legend">'+data.map((x,i)=>'<div><i style="background:'+colors[i%colors.length]+'"></i><span>'+esc(x.name)+'</span><b>'+x.trades+'</b></div>').join("")+'</div></div>';}
function qualityCard(label,value,detail,cls=""){return '<div class="quality-card '+cls+'"><span>'+label+'</span><strong>'+value+'</strong><small>'+detail+'</small></div>';}

export function renderAnalytics(trades,m){
 const b=analyzeBehavior(trades),s=behaviorSummary(b),pf=b.equity?.profitFactor,dd=b.equity?.maxDrawdown||0,expectancy=b.expectancy||0,payoff=b.payoff;
 const setupRows=b.setups.length?b.setups.map(x=>'<div class="behavior-row"><div><b>'+esc(x.name)+'</b><small>'+x.trades+' reviewed · '+pct(x.winRate)+' win rate · '+(x.avgR==null?'R unavailable':formatR(x.avgR))+'</small></div><strong class="'+(x.pnl>=0?"up":"down")+'">'+signed(x.pnl)+'</strong></div>').join(""):'<div class="empty-state">Review trades from the drawer to build your setup history.</div>';
 const gradeRows=b.grades.length?b.grades.map(x=>'<div class="behavior-row"><div><b>Grade '+esc(x.name)+'</b><small>'+x.trades+' trades · '+pct(x.winRate)+' win rate</small></div><strong class="'+(x.pnl>=0?"up":"down")+'">'+signed(x.pnl)+'</strong></div>').join(""):'<div class="empty-state">Add execution grades in post-trade reviews.</div>';
 const ruleRows=b.rules.map(x=>'<div class="behavior-row"><div><b>'+esc(x.name)+'</b><small>'+x.count+' followed · '+x.recorded+' explicitly recorded</small></div><strong>'+(x.count?pct(x.winRate):"—")+'</strong></div>').join("");
 const flagRows=b.flags.map(x=>'<div class="flag '+x.type+'"><span>'+(x.type==="risk"?"◈":x.type==="behavior"?"↻":x.type==="streak"?"!":"✦")+'</span><div><b>'+esc(x.title)+'</b><p>'+esc(x.text)+'</p></div></div>').join("");
 return '<div class="page-title"><div><div class="kicker">BEHAVIORAL ANALYTICS</div><h1>Your trading fingerprint</h1><p class="sub">The machine compares instruments, sessions, sequences, risk and your reviews.</p></div><button class="ghost" data-view="trades">Review more trades</button></div>'+ 
 '<div class="analytics-grid"><div class="panel"><span class="kicker">REVIEW COVERAGE</span><h2>'+s.coverage+'</h2><div class="score">'+b.reviewedCount+' / '+trades.length+'</div><div class="meter"><i style="width:'+Math.min(b.reviewCoverage,100)+'%"></i></div></div><div class="panel"><span class="kicker">INTELLIGENCE CONFIDENCE</span><h2>'+s.confidence+' / 100</h2><div class="score confidence-'+s.confidenceLabel.toLowerCase()+'">'+esc(s.confidenceLabel)+'</div><div class="meter"><i style="width:'+s.confidence+'%"></i></div><small class="confidence-note">Based on sample size, review coverage and risk-data coverage. It measures evidence quality, not strategy quality.</small></div></div>'+ 
 '<div class="quality-strip">'+qualityCard("EXPECTANCY",(expectancy>=0?"+":"")+money(expectancy),b.tradeCount+" executions · average outcome",expectancy>=0?"positive":"negative")+qualityCard("PROFIT FACTOR",pf==null?"—":pf.toFixed(2),"gross profit ÷ gross loss",pf!=null&&pf>=1?"positive":"negative")+qualityCard("PAYOFF RATIO",payoff==null?"—":payoff.toFixed(2)+"×","average win ÷ average loss",payoff!=null&&payoff>=1?"positive":"")+qualityCard("CONSISTENCY",s.consistency+" / 100","outcome dispersion index",s.consistency>=65?"positive":s.consistency<45?"negative":"")+qualityCard("MAX DRAWDOWN",money(dd),"peak-to-trough in sample",dd>0?"risk":"")+'</div>'+ 
 '<div class="chart-grid-2"><div class="panel"><div class="panel-head"><div><span class="kicker">P&L BY INSTRUMENT</span><h2>Where the money is moving</h2></div></div>'+bars(b.bySymbol)+'</div><div class="panel"><div class="panel-head"><div><span class="kicker">TRADE MIX</span><h2>Instrument share</h2></div></div>'+pie(b.bySymbol)+'</div></div>'+ 
 '<div class="chart-grid-2"><div class="panel"><span class="kicker">SESSION PERFORMANCE</span><h2>London vs New York vs Asia</h2>'+bars(b.bySession)+'</div><div class="panel"><span class="kicker">DIRECTION</span><h2>Buy vs sell</h2>'+bars(b.bySide)+'</div></div>'+ 
 '<div class="behavior-grid"><div class="panel"><span class="kicker">SETUP LAB</span><h2>Reviewed setup performance</h2><div class="behavior-list">'+setupRows+'</div></div><div class="panel"><span class="kicker">EXECUTION GRADES</span><h2>Grade vs outcome</h2><div class="behavior-list">'+gradeRows+'</div></div><div class="panel"><span class="kicker">RULE ADHERENCE</span><h2>Rules become measurable</h2><div class="behavior-list">'+ruleRows+'</div></div><div class="panel"><span class="kicker">MACHINE SIGNALS</span><h2>What deserves a closer look</h2><div class="flag-list">'+flagRows+'</div></div></div>'+ 
 '<div class="analytics-footnote"><span>DATA DISCIPLINE</span><p>Metrics describe the loaded sample only. Expectancy, profit factor, consistency and drawdown are historical observations, not forecasts or guarantees.</p></div>';
}

export function renderInsights(trades,m){
 const b=analyzeBehavior(trades),s=behaviorSummary(b),initial=answerQuestion("overview",trades),flags=b.flags.slice(0,5),setups=b.setups.filter(x=>x.trades>=2).slice(0,4);
 return '<div class="page-title ai-command-title"><div><div class="kicker">TRADING INTELLIGENCE · AI COMMAND CENTER</div><h1>Trading Analyst</h1><p class="sub">A decision-support layer built from your journal, behavior and live market context.</p></div><div class="ai-live-pill"><i class="live-dot"></i><span id="aiMarketStatus">MARKET ENGINE CHECKING</span></div></div>'+ 
 '<div class="ai-command-grid"><div class="panel ai-regime-card"><div class="kicker">MARKET REGIME</div><h2 id="aiRegime">Connecting…</h2><p id="aiRegimeText" class="sub">Waiting for the live scanner. No regime is assumed when the engine is offline.</p><div class="regime-meter"><i id="aiRegimeMeter" style="width:0%"></i></div></div><div class="panel"><div class="kicker">CURRENT EDGE</div><h2>'+esc(s.strongestSetup)+'</h2><p class="sub">'+esc(s.coverage)+' review coverage · '+trades.length+' executions in the sample.</p><div class="ai-mini-stats"><div><span>AVG R</span><b>'+(b.setups[0]?formatR(b.setups[0].avgR):"—")+'</b></div><div><span>RISK</span><b>'+s.riskConsistency+'</b></div><div><span>CONSISTENCY</span><b>'+s.consistency+'</b></div></div></div></div>'+ 
 '<div class="ai-command-grid ai-command-grid-main"><div class="panel"><div class="panel-head"><div><span class="kicker">AI OBSERVATIONS</span><h2>What the machine sees</h2></div><span class="ai-orb">✦</span></div><div class="ai-observation-list">'+flags.map(x=>'<div class="ai-observation"><span>'+(x.type==="risk"?"◈":x.type==="behavior"?"↻":x.type==="streak"?"!":"✦")+'</span><div><b>'+esc(x.title)+'</b><p>'+esc(x.text)+'</p></div></div>').join("")+'</div></div><div class="panel"><div class="kicker">SETUP PERFORMANCE</div><h2>Your reviewed edge</h2><div class="ai-setup-list">'+(setups.length?setups.map(x=>'<div><div><b>'+esc(x.name)+'</b><small>'+x.trades+' trades · '+pct(x.winRate)+' win rate</small></div><strong class="'+(x.pnl>=0?"up":"down")+'">'+signed(x.pnl)+'</strong></div>').join(""):'<div class="empty-state">Review more trades to let the analyst compare setups.</div>')+'</div></div></div>'+ 
 '<div class="panel ai-market-context"><div class="panel-head"><div><span class="kicker">LIVE MARKET CONTEXT</span><h2>Scanner intelligence</h2></div><button class="text-btn" data-view="radar">Open Market Radar →</button></div><div id="aiMarketQueue" class="ai-market-queue"><div class="empty-state">Waiting for market engine…</div></div></div>'+ 
 '<div class="coach-shell"><div class="coach-header"><div class="analyst-orb">✦</div><div><span class="kicker">ASK TRADEDEN</span><h2>What do you want to understand?</h2><p class="sub">Answers are calculated from executions and reviews stored in this workspace.</p></div></div><div class="coach-prompts"><button data-question="Why have I been losing?">Why have I been losing?</button><button data-question="What happens after I take a loss?">After a loss?</button><button data-question="Which setups make me money?">Which setups work?</button><button data-question="Am I risking consistently?">Is my risk consistent?</button></div><form class="coach-ask" id="coachForm"><input id="coachInput" placeholder="Ask: what is my biggest recurring mistake?" autocomplete="off"/><button class="primary">Ask</button></form><div class="coach-answer" id="coachAnswer"><div class="kicker">DATA ANSWER</div><h3>'+esc(initial.title)+'</h3><p>'+esc(initial.body)+'</p>'+(initial.facts.length?"<ul>"+initial.facts.map(x=>"<li>"+esc(x)+"</li>").join("")+"</ul>":"")+'</div><div class="coach-feed">'+flags.map(x=>'<div class="coach-item"><span>✦</span><div><b>'+esc(x.title)+'</b><p>'+esc(x.text)+'</p></div></div>').join("")+'</div><div class="analyst-grid"><div><span>REVIEW COVERAGE</span><b>'+s.coverage+'</b></div><div><span>INTELLIGENCE CONFIDENCE</span><b>'+s.confidence+'/100</b></div><div><span>RISK CONSISTENCY</span><b>'+s.riskConsistency+'</b></div></div></div>';
}

async function paintAI(){const status=document.getElementById("aiMarketStatus"),queue=document.getElementById("aiMarketQueue");if(!status||!queue)return;try{const data=await engineFetch("/api/market/radar"),markets=(data.markets||[]).filter(x=>x.state!=="NO SETUP").sort((a,b)=>(b.score||0)-(a.score||0)).slice(0,6);status.textContent=data.live?"LIVE MT5 ENGINE":"ENGINE ONLINE";const focus=markets[0];document.getElementById("aiRegime").textContent=focus?(focus.direction==="LONG"?"Bullish opportunity map":"Bearish opportunity map"):"No active setup";document.getElementById("aiRegimeText").textContent=focus?focus.symbol+" is currently the highest-scoring monitored setup at "+focus.score+"/100. This is a scanner observation, not an execution signal.":"The engine is online, but no monitored market currently meets the scanner threshold.";document.getElementById("aiRegimeMeter").style.width=(focus?Math.min(focus.score,100):0)+"%";queue.innerHTML=markets.length?markets.map(x=>'<div class="ai-market-row"><div><b>'+esc(x.symbol)+'</b><small>'+esc(x.setup||"No setup")+' · '+esc(x.direction||"WATCH")+'</small></div><span class="radar-state '+String(x.state||"").toLowerCase().replace(/\s+/g,"-")+'">'+esc(x.state)+'</span><strong>'+Number(x.score||0)+'</strong></div>').join(""):'<div class="empty-state">No qualifying setups right now.</div>';}catch(_){status.textContent="ENGINE OFFLINE";document.getElementById("aiRegime").textContent="Waiting for engine";document.getElementById("aiRegimeText").textContent="Connect the MT5 engine from Market Radar to unlock live market context.";document.getElementById("aiRegimeMeter").style.width="0%";queue.innerHTML='<div class="empty-state">Live market context is unavailable. Your journal intelligence remains active.</div>';}}
export function initInsights(){paintAI();}
